### PR TITLE
Make mess a compiled library

### PR DESCRIPTION
**Pull request by fishinthecalculator**
I'm not sure this is desirable at all, but I'm in the process of packaging Bonfire for Guix at https://github.com/fishinthecalculator/bonfire-guix (which I would like to include in bonfire repositories if there is interest).

This PR allows mess to be loaded just like other dependencies during the build of an Elixir package instead of having to drop the file around. It would be nice to make a release after this change since the code seems stable from some years but this is a nice to have imo. The ability to compile mess to a `.beam` file is already enough,

thanks for all your work :)

### CODE REVIEW

**Comment by mayel** [comment]
Thanks for the contribution! While these changes make sense for presentational purposes, I don't see how we can avoid having the file in each repo and including it in each `mix.exs` with `Code.eval_file` because this code needs to run before any dependencies are fetched since it is used to fetch (the list of) dependencies (and also `mix.exs` is run before any already fetched dependencies are loaded, so it is not possible to use any other module/function in that context). 

Also noting that the `mess.exs` included in the main repo is a slightly longer/more complex version of the script to handle some extra cases (along with the sister script `Bonfire.Mixer`) that aren't needed when running an extension independently...

**Comment by fishinthecalculator** [comment]
Hi @mayel , let me anticipate that my belief this is partly based on opinion and partly on experience. The owner of the provisioning of `Mess` is the same one that owns the provisioning of `mix` , so Nix/Guix/homebrew. This is how I am building `bonfire_data_edges` [inside Guix](https://github.com/fishinthecalculator/bonfire-guix/blob/main/modules/bonfire/packages/bonfire-libraries.scm#L79) for example.

I agree that having to maintain a package inside a system package manager is additional effort so maybe cleanest the way forward is to look into how Mix extensions are supposed to be shipped though Mix (i.e. just like it is possible to ship Rust cargo extension through cargo )?

Finally I apologize , I didn't notice that the mess code in the main project is different. Do you think it make sense to continue in this effort of making `mess` a full Mix extension? Next steps could be:

- figure out how to deliver Mix extensions through Mix
- Bring the code that is only in main projects' mess over here
- making a named release for mess

**Comment by mayel** [comment]
Sorry I'm not following, maybe because I'm not a nix/guix user, what do you mean by mix extensions?

**Comment by mayel** [comment]
In general though, I'm not sure it's worth the effort? Apart from the edge cases in the main app, this script is quite basic and hasn't needed any changes since first written...

**Comment by fishinthecalculator** [comment]
No it's probably me not knowing enough about Mix. In other languages package managers there is a concept of extending the tool, to implement new logic or extend existing behaviour. I'm thinking of things such  as https://doc.rust-lang.org/book/ch14-05-extending-cargo.html or https://developer.android.com/build/releases/gradle-plugin or https://python-poetry.org/docs/plugins/ where you have packages modifying the package manager behaviour.

I'm not sure whether Mix allows such an extension behaviour, so if it does not then the case is closed and the answer is to bootstrap mess with system package managers, but in the case Mix *does* have the ability to load custom code extending it's behaviour I'd look into that.

If the effort is not worth then no problem :)

**Comment by mayel** [comment]
Ah I see, well there's [Mix tasks](https://hexdocs.pm/mix/1.17.3/Mix.Task.html) but those are for adding extra commands to the tool (eg. `mix docs` or `mix localise`) but with Mess we're actually simply generating the list of dependencies which are usually defined in a function inside the `mix.exs` module, and I don't think that's a candidate for a mix task.

**Pull request merged**
